### ISSUE TITLE
Error: 'CompletionUsage' object has no attribute 'prompt_tokens_details'

### ISSUE THREAD

**Issue by caustiq** [hekmon/comfyui-openai-api#5]
Works fine in 2.0.0, but in 2.0.1 it throws:

```
!!! Exception during processing !!! 'CompletionUsage' object has no attribute 'prompt_tokens_details'
Traceback (most recent call last):
  File "/home/user/ComfyUI/execution.py", line 515, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ComfyUI/execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ComfyUI/execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/home/user/ComfyUI/execution.py", line 291, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/home/user/ComfyUI/comfy_api/internal/__init__.py", line 149, in wrapped_func
    return method(locked_class, **inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ComfyUI/comfy_api/latest/_io.py", line 1513, in EXECUTE_NORMALIZED
    to_return = cls.execute(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ComfyUI/custom_nodes/openai-api/completions.py", line 323, in execute
    stats = format_usage(completion.usage)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ComfyUI/custom_nodes/openai-api/completions.py", line 37, in format_usage
    if usage.prompt_tokens_details is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ComfyUI/venv/lib/python3.12/site-packages/pydantic/main.py", line 984, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CompletionUsage' object has no attribute 'prompt_tokens_details'
```
